### ISSUE TITLE
Problem with relative path

### ISSUE THREAD

**Issue by LynxDelli** [klei/gulp-inject#100]
What I try 
get index.html file 
inject js file from build directory
copy index file to build directory

```Script
    gulp.src('./web/index.html')
      .pipe(inject(gulp.src(['./build/ui/js/vendors.js'], {read: false})))
      .pipe(gulp.dest('./build/ui'));
```
As a result I get:
```Script
<script src="/build/ui/js/vendors.js"></script>
```

And I want this:
```Script
<script src="js/vendors.js"></script>
```

Any help?

**Comment by chocolateslice** [comment]
By chance I was just using inject for the first time and ran into a similar issue.

If you change it to this:

    gulp.src('./web/index.html')
      .pipe(inject(gulp.src(['./build/ui/js/vendors.js'], {read: false}), {relative: true}))
      .pipe(gulp.dest('./build/ui'));

It'll make the path relative to the .web/index.html which I think should work.

**Comment by joakimbeng** [comment]
Actually I don't think the `relative` option will work in this case, because that will inject a path like `../build/ui/js/vendors.js`, i.e. the injected path is relative to the source (`./web/index.html`) and not the destination (`./build/ui`).

I think the correct solution should use `ignorePath` and `addRootSlash=false`, like this:

```javascript
gulp.src('./web/index.html')
  .pipe(inject(gulp.src(['./build/ui/js/vendors.js'], {read: false}), {ignorePath: 'build/ui', addRootSlash: false}))
  .pipe(gulp.dest('./build/ui'));
```

**Comment by Kroid** [comment]
don't worked:

```javascript
.pipe(inject(gulp.src('app/**/*.js'), {read: false}), {ignorePath: 'app', addRootSlash: false})
```

result:
```html
<script src="/app/app.js"></script>
```
