### ISSUE TITLE
Removing html-comment after injection

### ISSUE THREAD

**Issue by frodefi** [klei/gulp-inject#102]
I guess there is no reason to keep the   after injection, so if would be nice to have them removed, or at least an option for having them removed (I do not want for my clients (and their clients) to see unnecessary and irrelevant stuff).

**Comment by j-brown** [comment]
But what happens when you have additional things that need to be injected down the line? You'd have to manually place these comments back in.
You need something like gulp-minify-html, to clean up the source for distribution. That shouldn't really be a part of gulp-inject though.

**Comment by frodefi** [comment]
That seems logical, thanks!

**Comment by joakimbeng** [comment]
Thanks @j-brown !
