### ISSUE TITLE
Inject jsx into html

### ISSUE THREAD

**Issue by corintho** [klei/gulp-inject#104]
I noticed you have the ability to inject numerous files into html, but jsx is not one of them.
I find that for development workflow, it is interesting to be able to inject JSX files themselves into HTML, and allow the browser-based transform tool to handle everything in runtime.
I used a slightly modified function for injection, based on the js one, but applying the proper script type to the included file.
If it is a wanted feature, let me know and I assemble a PR with the code change and appropriate tests.

**Comment by joakimbeng** [comment]
Sounds like a good idea! I'm looking forward to the PR then ;)
