### ISSUE TITLE
Inject CSS files in a specific order.

### ISSUE THREAD

**Issue by HarrisRobin** [klei/gulp-inject#112]
Hi,

So one problem I see with injecting SASS/CSS files, and I don't know if anyone's solved this is the order the files are being injected in. Sometimes, a SASS file depends on another (for example, in a modular CSS architecture you might have a mixins folder that needs to be injected before a lot of other folders). Manually importing those files before the inject comment seems to work but it also duplicates the code (importing it twice). Has anyone found a solution for this?

Thanks

**Comment by joakimbeng** [comment]
See the code example in the [deprecated sort option section](https://github.com/klei/gulp-inject#optionssort).

Also regarding SASS files I suggest you compile your files into a single file and inject only that and let SASS handle the correct ordering of files.
