### ISSUE TITLE
gulp-inject says 11 files injected, nothing happens though.

### ISSUE THREAD

**Issue by jchayan** [klei/gulp-inject#113]
I have the following simple task

    var src = './src';
    var vendor = './res/vendor';

    gulp.task('index', function () {
        var target = gulp.src(path.join(src, 'index.html')); 

        var vendorDirs = getFolders(vendor); // get all tree directory structure from res/vendor
        vendorDirs = matchSuffix(vendorDirs, '/*.min.js'); // suffix (i.e.) extension to filter scripts

        var appDirs = getFolders(src);
        appDirs = matchSuffix(appDirs, '/*.js');

        var files = vendorDirs.concat(appDirs); // files to be injected
        var sources = gulp.src(files, {read: false});
        // console.log(files); See below

        return target.pipe(inject(sources))
        .pipe(gulp.dest(src));
    }); 

Running `gulp index` I get the following output:

gulp-inject 11 files into index.html.
[19:47:34] Finished 'index' after 102 ms

Even so, When I check the index.html file. It has no injects, I doesn't even have the <inject> comments

The array I pass as the sources to be injected (`files`) prints to the console as follows:

[ 'res/vendor/angular/*.min.js',
  'res/vendor/angular-ui-router/*.min.js',
  'res/vendor/bootstrap/*.min.js',
  'res/vendor/components-font-awesome/*.min.js',
  'res/vendor/jquery/*.min.js',
  'res/vendor/less/*.min.js',
  'res/vendor/ngstorage/*.min.js',
  'res/vendor/angular-ui-router/api/*.min.js',
  'res/vendor/angular-ui-router/release/*.min.js',
  'res/vendor/angular-ui-router/src/*.min.js',
  'res/vendor/bootstrap/dist/*.min.js',
  'res/vendor/bootstrap/fonts/*.min.js',
  'res/vendor/bootstrap/grunt/*.min.js',
  'res/vendor/bootstrap/js/*.min.js',
  'res/vendor/bootstrap/less/*.min.js',
  'res/vendor/bootstrap/dist/css/*.min.js',
  'res/vendor/bootstrap/dist/fonts/*.min.js',
  'res/vendor/bootstrap/dist/js/*.min.js',
  'res/vendor/bootstrap/less/mixins/*.min.js',
  'res/vendor/components-font-awesome/css/*.min.js',
  'res/vendor/components-font-awesome/fonts/*.min.js',
  'res/vendor/components-font-awesome/less/*.min.js',
  'res/vendor/components-font-awesome/scss/*.min.js',
  'res/vendor/jquery/dist/*.min.js',
  'res/vendor/jquery/src/*.min.js',
  'res/vendor/jquery/src/ajax/*.min.js',
  'res/vendor/jquery/src/attributes/*.min.js',
  'res/vendor/jquery/src/core/*.min.js',
  'res/vendor/jquery/src/css/*.min.js',
  'res/vendor/jquery/src/data/*.min.js',
  'res/vendor/jquery/src/effects/*.min.js',
  'res/vendor/jquery/src/event/*.min.js',
  'res/vendor/jquery/src/exports/*.min.js',
  'res/vendor/jquery/src/manipulation/*.min.js',
  'res/vendor/jquery/src/queue/*.min.js',
  'res/vendor/jquery/src/sizzle/*.min.js',
  'res/vendor/jquery/src/traversing/*.min.js',
  'res/vendor/jquery/src/var/*.min.js',
  'res/vendor/jquery/src/ajax/var/*.min.js',
  'res/vendor/jquery/src/core/var/*.min.js',
  'res/vendor/jquery/src/css/var/*.min.js',
  'res/vendor/jquery/src/manipulation/var/*.min.js',
  'res/vendor/jquery/src/sizzle/dist/*.min.js',
  'res/vendor/jquery/src/traversing/var/*.min.js',
  'res/vendor/jquery/src/ajax/var/*.min.js',
  'res/vendor/jquery/src/core/var/*.min.js',
  'res/vendor/jquery/src/css/var/*.min.js',
  'res/vendor/jquery/src/manipulation/var/*.min.js',
  'res/vendor/jquery/src/sizzle/dist/*.min.js',
  'res/vendor/jquery/src/traversing/var/*.min.js',
  'res/vendor/less/dist/*.min.js',
  'res/vendor/bootstrap/dist/css/*.min.js',
  'res/vendor/bootstrap/dist/fonts/*.min.js',
  'res/vendor/bootstrap/dist/js/*.min.js',
  'res/vendor/bootstrap/less/mixins/*.min.js',
  'res/vendor/jquery/src/ajax/*.min.js',
  'res/vendor/jquery/src/attributes/*.min.js',
  'res/vendor/jquery/src/core/*.min.js',
  'res/vendor/jquery/src/css/*.min.js',
  'res/vendor/jquery/src/data/*.min.js',
  'res/vendor/jquery/src/effects/*.min.js',
  'res/vendor/jquery/src/event/*.min.js',
  'res/vendor/jquery/src/exports/*.min.js',
  'res/vendor/jquery/src/manipulation/*.min.js',
  'res/vendor/jquery/src/queue/*.min.js',
  'res/vendor/jquery/src/sizzle/*.min.js',
  'res/vendor/jquery/src/traversing/*.min.js',
  'res/vendor/jquery/src/var/*.min.js',
  'res/vendor/jquery/src/ajax/var/*.min.js',
  'res/vendor/jquery/src/core/var/*.min.js',
  'res/vendor/jquery/src/css/var/*.min.js',
  'res/vendor/jquery/src/manipulation/var/*.min.js',
  'res/vendor/jquery/src/sizzle/dist/*.min.js',
  'res/vendor/jquery/src/traversing/var/*.min.js',
  'res/vendor/jquery/src/ajax/var/*.min.js',
  'res/vendor/jquery/src/core/var/*.min.js',
  'res/vendor/jquery/src/css/var/*.min.js',
  'res/vendor/jquery/src/manipulation/var/*.min.js',
  'res/vendor/jquery/src/sizzle/dist/*.min.js',
  'res/vendor/jquery/src/traversing/var/*.min.js',
  'res/vendor/jquery/src/ajax/var/*.min.js',
  'res/vendor/jquery/src/core/var/*.min.js',
  'res/vendor/jquery/src/css/var/*.min.js',
  'res/vendor/jquery/src/manipulation/var/*.min.js',
  'res/vendor/jquery/src/sizzle/dist/*.min.js',
  'res/vendor/jquery/src/traversing/var/*.min.js',
  'src/common/*.js',
  'src/dashboard/*.js',
  'src/login/*.js',
  'src/common/js/*.js',
  'src/common/services/*.js' ]

This should actually resolves to 11 files as correctly reported by gulp, but then is the index.html not changing at all?

Thanks in advance.

**Comment by kengz** [comment]
same problem here. +1

**Comment by kengz** [comment]
@jchayan Hey I just found out from a friend that you actually need to include those comments in the html files, like these:

```
<!-- inject:js -->
<!-- endinject -->
```

**Comment by joakimbeng** [comment]
Not an issue. This is documented as [Basic Usage](https://github.com/klei/gulp-inject#basic-usage).
