### ISSUE TITLE
Clean between the tags before injecting again

### ISSUE THREAD

**Issue by Alber70g** [klei/gulp-inject#114]
I'm not sure if I'm missing something obvious, but sometimes I remove files and there is still a reference in the `index.html` to them. Aren't they removed automatically (clean before inject) or should I put a boolean to true?

**Comment by cafesanu** [comment]
Hi, experiencing same issue. Any advice or answer to this issue?

**Comment by Alber70g** [comment]
What I did was creating an empty index.git.html and create a destination index.html. The .git. version I add to the repository, where I leave the latter one outside.

**Comment by joakimbeng** [comment]
Are you using any gulp cache plugins? `gulp-inject` itself does not cache anything and always replaces the complete `<starttag><old injects><endtag>` with `<starttag><new injects><endtag>`...

**Comment by cafesanu** [comment]
For reasons hard and long to explain (big gulp project with multiple modules) sometimes I want the inject src files not to exist
Suppose my source index.html page has the following tag, and sometimes-this-file-exists.js DOES exists at the moment :

    
    

If I run my inject task containing this:

    return gulp
    .src(app.dir + '/src/main/index.html')
    .pipe($.inject(gulp.src('/src/sometimes-this-file-exists.js', {read: false}), {
        starttag: ''
    }))
    .pipe(gulp.dest(app.dir + '/src/main'));
 my index.html now has:

    
    <script src="src/sometimes-this-file-exists.js"></script>
    

Now, suppose, for a reason, sometimes-this-file-exists.js is deleted from src directory. If I run my gulp task, I would expect the tag to be empty, like this:

    
    

But, instead it is still:

    
    <script src="src/sometimes-this-file-exists.js"></script>
    

**Yes, I know that src and dest are the same, but for reasons out of my hand, it needs to be like that**

So, the question remains.... Is there an option to delete what was previously inside the tags?

Thanks!

**Comment by Artmobile** [comment]
Still happens when an empty _sources_ parameter is provided. I expect the content between the starttag and endtag be cleaned in that case.

**Comment by joakimbeng** [comment]
@Artmobile have you tried using the [empty option](https://github.com/klei/gulp-inject/blob/master/README.md#optionsempty)? 
It should do what you want, but be aware of that it can empty more than anticipated (see the link above)
