### ISSUE TITLE
Injection src === dest possible?

### ISSUE THREAD

**Issue by kokujin** [klei/gulp-inject#115]
Is it possible to inject assets using the same source path and destination path? I would like to modify my source HTML templates in place without moving them to another directory.

Thanks

**Comment by willpracht** [comment]
I believe this should work:

```js
...
// $.inject = require('gulp-inject');
...
gulp.src('./app/index.html')
  .pipe($.inject(gulp.src('./app/components/users/**/*.js', {
    read: false
  })))
  .pipe(gulp.dest('./app/index.html');
...
```

**Comment by joakimbeng** [comment]
As @willpracht says it's possible using `gulp.dest`, it takes a folder as a parameter and not a file though. So it should be:

```javascript
...
// $.inject = require('gulp-inject');
...
gulp.src('./app/index.html')
  .pipe($.inject(gulp.src('./app/components/users/**/*.js', {
    read: false
  })))
  .pipe(gulp.dest('./app');
...
```

**Comment by willpracht** [comment]
Nice catch! 😊
