### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by poliveira89** [klei/gulp-inject#116]
_Disclaimer:_
I created a project using a Yeoman Generator [generator-gulp-angular](https://github.com/Swiip/generator-gulp-angular)
I'm using the following version: Nodejs(v0.12.2), NPM (2.7.5), Gulp (3.9.0) and gulp-inject (1.3.1)

_Problem:_
Every time I execute `gulp serve` to display my page the process struggles to pass over a task named "styles" which at the first `.pipe()` executes `$.inject()` regarding to `gulp-inject` of only 5 LESS files and then this error appears:

``` bash
[14:53:21] Using gulpfile ~/my-portal/gulpfile.js
[14:53:21] Starting 'scripts'...
[14:53:22] Starting 'styles'...
[14:53:22] gulp-inject 5 files into index.less.
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
[1]    3680 abort      gulp serve
```

and the process exits.

Note1: I have tried other projects with `gulp` and `gulp-inject` and they work.
Note2: I have updated globally `gulp` and locally `gulp-inject` to the latest versions.

**Comment by joakimbeng** [comment]
If you comment out the `$.inject`-pipe does it complete then? If not take it back and comment the `wiredep`-line instead, does that help?
What happens if you run only the `styles` task?

**Comment by shuangshan** [comment]
I also encountered such issue, only run styles is the same, I have 57 less files. comment out the $.inject-pipe or wiredep hte issue will gone.

**Comment by rejas** [comment]
Is this still happening to you with the latest version? What versions of this plugin and node etc are you using?

**Comment by blowsie** [comment]
I narrowed my problem down to gulp-uglify consuming a large amount of memory when concatenating and uglifing my large SPA (500+ JS files).  I fixed my issue by setting node arguments when using the gulp task.
`gulp build --max_old_space_size=4096`
