### ISSUE TITLE
Globbing patterns stopped working

### ISSUE THREAD

**Issue by gigablox** [klei/gulp-inject#120]
```js
index: {  
    src: dest + "/index.html",
    dest: dest,
    sources:[
      dest+'/css/*.css',
      dest+'/js/jquery.js',
      dest+'/js/!(app.js|bootstrap.js)*.js',
      dest+'/js/app.js',
      dest+'/js/bootstrap.js'
    ],
    options:{
      ignorePath:['/www'],
      addRootSlash:false
    }
  },
```

Out of nowhere globbing patterns stopped working. Have not changed my manifest at all. Was wondering if you are aware of any `gulp` dependencies that changed or if any of your project dependencies are pointing to latest that would cause this behavoir.

**Comment by joakimbeng** [comment]
gulp-inject has nothing to do with glob patterns, it just handles all files in the piped stream. If you're having an issue with that there's probably an issue with the gulp.src function or where you're using `index.sources` from your snippet.
