### ISSUE TITLE
No option to make paths relative to generated file

### ISSUE THREAD

**Issue by heyallan** [klei/gulp-inject#124]
Not sure if I'm getting the hang of if, so I better ask:

**Assuming the following structure:**

```
gulpfile.js
src/
  index.html
lib/
  vendor.css
build/
  generated.html
```

**There's option to make paths relative to:**

- source (injected file) where path maps from `./gulpfile.js` to `lib/vendor.css` (default)
- target (working file) where path maps from `src/index.html` to `lib/vendor.css`

**But there's NO option to make paths relative to:**

- dest (generated file) where path maps from `build/generated.html` to `lib/vendor.css`

Is this true? **Please confirm**

**Comment by joakimbeng** [comment]
Yes, that's because it is impossible for this plugin to know what you pipe it to.
You can accomplish what you want using a combination of the ignorePath, addPrefix and relative options though.

**Comment by heyallan** [comment]
Thank you :v:
