### ISSUE TITLE
removing of path parts do not work in certain cases

### ISSUE THREAD

**Issue by garmoshka-mo** [klei/gulp-inject#125]
Here is example:
https://github.com/garmoshka-mo/gulp-inject-noeffect/blob/master/gulpfile.js

Seems, it is related to missing './' in front of path - in this case none of method works, which described here:
https://github.com/klei/gulp-inject/wiki/Clarifying-injected-paths

It creates confusion. More convenient would be to let system handle paths in predictable way as soon as path designate some real file (which gulp itself may access).

**Comment by joakimbeng** [comment]
No, it has nothing to do with `"./"` in front of the path. `gulp.src` resolves that to a full path anyway...

It would help if you gave some info about expected result and actual result.

But I'll give it a try anyway... I think you're experiencing injects which contains `"../build/"` and you just want `"build/"` am I right?
The `"relative"` option makes `gulp-inject` inject paths for sources (`"build/scripts.js"`) relative to the target (`"app/index.html"`). And to go from "app/" to "build/" the path will be "../build/".

**Comment by garmoshka-mo** [comment]
No, i build all my things to folder with name "build" - this is the result, which will go to static hosting.
So i want all files there (minimized, etc) and HTML linked to them.
What i expect in my example is to have 
    <script src="scripts.js"></script>
not
    <script src="/build/scripts.js"></script>

https://github.com/garmoshka-mo/gulp-inject-noeffect/blob/master/gulpfile.js
Even if i add build dest 2 times:

        .pipe(gulp.dest(outputFolder))
        .pipe(inject(sources), {relative: true})
        .pipe(gulp.dest(outputFolder));

Still do not work. Though, when i do like this:

````
gulp.task('index', function() {
    var sources = gulp.src([
        './'+outputFolder+'/scripts.js',
        './'+outputFolder+'/css.css'
    ], {read: false});

    return gulp.src('./app/index.html')
        .pipe(gulp.dest('./'+outputFolder))
        .pipe(inject(sources, {relative: true}))
        .pipe(gulp.dest('./'+outputFolder));
});
````

Then it do what i want

**Comment by joakimbeng** [comment]
I think I've located the problem... The inject options on [line 41](https://github.com/garmoshka-mo/gulp-inject-noeffect/blob/master/gulpfile.js#L41) should be placed within `inject()`'s parentheses. But in your case you actually don't need the `relative` option, if you instead set `cwd` to `outputFolder` for `sources = gulp.src` (must be a full path, see below).

So a task like this should work:

```javascript
gulp.task('index', function() {
    var sources = gulp.src([
        'scripts.js',
        'css.css'
    ], {read: false, cwd: __dirname + '/' + outputFolder});

    return gulp.src('./app/index.html')
        .pipe(inject(sources))
        .pipe(gulp.dest(outputFolder));
});
```

Hope that helps!

**Comment by garmoshka-mo** [comment]
yeah, you are right - didn't noticed wrong parentheses
both approaches works, thank you for help!

**Comment by joakimbeng** [comment]
@garmoshka-mo :+1: no problem!
