### ISSUE TITLE
version 1.4.0 is missing from npm

### ISSUE THREAD

**Issue by alinz** [klei/gulp-inject#126]
Hello,
My project is depends on 1.4.0 on npm and it seems that you accidentally removed it from npm.

`https://registry.npmjs.org/gulp-inject/1.4.0` returns 404!

Any reasons?
thanks

**Comment by joakimbeng** [comment]
Weird, I haven't run such a command... I recommend using 1.5.0 instead.

**Comment by alinz** [comment]
Thanks, it used to work. The thing is 1.3.0 and 1.5.0 is in npm but 1.4.0 is not. I have upgraded to 1.5.0 and works perfectly. For consistency, would you upload 1.4.0 to npm as well?
