### ISSUE TITLE
Inject doesn’t remove deleted files from the html if there’s no one left

### ISSUE THREAD

**Issue by zhekaus** [klei/gulp-inject#128]
For instance, If I remove all the css files injected, angular-inject lives them in an html file. However, if I add one, inject perfectly refreshes the file list in an html file.

**Comment by sergesemashko** [comment]
+1, have the same issue. Still have one file injected when there are no files in the stream. Content between inject tags is getting updated if stream is empty.

**Comment by LouisTakePILLz** [comment]
Experiencing the same issue here.

**Comment by joakimbeng** [comment]
Duplicate of #59
