### ISSUE TITLE
Leave order of existing files

### ISSUE THREAD

**Issue by mhtsbt** [klei/gulp-inject#130]
I would love to have an option that would not touch the current sorting of the files that I have manually included in my index.html

I have some scripts that needs to be included in a certain order which cannot be easyly mapped out with patterns. This option should simply when a new file is added, add it to the bottom.

**Comment by joakimbeng** [comment]
gulp-inject has nothing to do with the sort order of files, it injects them in the order they are streamed, e.g from gulp.src.
See the readme for example of how to sort the files before injection.
