### ISSUE TITLE
gulp-inject support injected order?

### ISSUE THREAD

**Issue by hjzheng** [klei/gulp-inject#133]
I check the johnpapa/generator-hottowel  's [gulpfile.js](https://github.com/johnpapa/generator-hottowel/blob/master/app/templates/_gulpfile.js) code, found following code:

```js
...
  .pipe(inject(config.js, '', config.jsOrder))
...
``` 
I did not find anything about this usage in README.md.
So I want to know that `gulp-inject` support injected order.

**Comment by joakimbeng** [comment]
That has nothing to do with this plugin, it just injects the files in the order it gets them. As the readme suggests you should [use something else to sort your files](https://github.com/klei/gulp-inject#optionssort).

They use another plugin for the sort order, see [L418 in their gulpfile](https://github.com/johnpapa/generator-hottowel/blob/master/app/templates/_gulpfile.js#L418).

**Comment by hjzheng** [comment]
thanks @joakimbeng

**Comment by johnnynode** [comment]
Refer to : https://github.com/klei/gulp-inject/issues/218
