### ISSUE TITLE
Is there any way to use both ignorePath and addRootSlash together?

### ISSUE THREAD

**Issue by alexkibler** [klei/gulp-inject#137]
I'm trying to inject all of the JS and CSS files from my build folder into my index.html (also in my build folder).  The relevant part of my gulp script looks like this:

```
    return gulp.src('index.html')
        .pipe(inject(gulp.src(['build/**/*.js','build/**/*.css'],{read:false}),{ignorePath:'build'}, {addRootSlash:false}))
        .pipe(gulp.dest('build'));
```

When that runs, my index.html ends up looking like this:

```
<!-- inject:js -->
    <script src="/app.min.js"></script>
    <script src="/bower_components/angular-resource.js"></script>
    <script src="/bower_components/angular-ui-router.js"></script>
    <script src="/bower_components/angular.js"></script>
    <script src="/bower_components/angularjs-typeahead-dropdown.js"></script>
    <script src="/bower_components/bootstrap.js"></script>
    <script src="/bower_components/jquery.js"></script>
    <script src="/bower_components/ui-bootstrap-tpls.js"></script>
    <!-- endinject -->
```

However, I need it to look like this:

```
<!-- inject:js -->
    <script src="app.min.js"></script>
    <script src="bower_components/angular-resource.js"></script>
    <script src="bower_components/angular-ui-router.js"></script>
    <script src="bower_components/angular.js"></script>
    <script src="bower_components/angularjs-typeahead-dropdown.js"></script>
    <script src="bower_components/bootstrap.js"></script>
    <script src="bower_components/jquery.js"></script>
    <script src="bower_components/ui-bootstrap-tpls.js"></script>
    <!-- endinject -->
```

Note the missing slash at the front of each file.  

How can I go about doing that?

**Comment by joakimbeng** [comment]
You have a typo in your code... You are providing two options objects (the latter with the `addRootSlash` option) when they should be merged into one.
That should fix your issue! (there's an existing unit test for this so I'm quite confident it works)

**Comment by alexkibler** [comment]
Thanks for the help!  That was definitely the issue.  I think I must've seen an incorrect example somewhere where people had multiple options objects rather than one object with multiple parameters.  Not sure why I thought that would work, but combining them into one definitely fixed it.
