### ISSUE TITLE
Removing injected files

### ISSUE THREAD

**Issue by yoooee** [klei/gulp-inject#138]
How do I remove the injected files?  They inject fine for testing, but for production, I would like to remove all the references and inject a single concatenated file.

Thanks.

**Comment by joakimbeng** [comment]
Have two different injection tasks, for instance:

```javascript
gulp.task('dev', function () {
  return gulp.src('app/index.html')
    .pipe(inject(gulp.src('app/files/**/*.{css,js}', {read: false})))
    .pipe(gulp.dest('app')); // the same destination as source for index.html above
});

gulp.task('prod', function () {
  return gulp.src('app/index.html')
    .pipe(inject(gulp.src('app/files/**/*.js').pipe(concat('app.js')).pipe(gulp.dest('build'))
    .pipe(inject(gulp.src('app/files/**/*.css').pipe(concat('app.css')).pipe(gulp.dest('build'))
    .pipe(gulp.dest('build'));
});
```

The above code could be simplified by putting stuff in separate functions though, but I hope you get the point.

**Comment by yoooee** [comment]
Thank you for the response.  My problem is that I'm using a framework that doesn't leverage separate folders for dev and prod.  They use the same folder and files.
