### ISSUE TITLE
Does app work without adding an endtag?

### ISSUE THREAD

**Issue by pgilad** [klei/gulp-inject#14]
Unless injecting into a non-html file (i.e the JSON example) I don't see any need to specify `<!-- endinject -->` in the html file.

So this pattern:

``` html
<!-- inject:js -->
<!-- any *.js files among your sources will go here as: <script src="FILE"></script> -->
<!-- endinject -->
```

Is the same as this one:

``` html
<!-- inject:js -->
```

But just shorter, more concise and less messy. The endtags IMO are a remnant of the `usemin` patterns where you actually specify all files **beforehand** unlike `gulp-inject` where files just come from a stream.

What do you think?

**Comment by specious** [comment]
On the other hand, the code would look a lot nicer without an endtag in the sources.

The script could replace `{starttag}` with `{transformed file}{starttag}` on each insertion if `endtag: null` is set. That would work with multiple files being injected, and all of them would appear in the right order.

It seems like using an endtag would be the less popular option if both ways are offered.

**Comment by specious** [comment]
The way it looks to me is there's no difference other than being able to have some content that will be removed between the tags.
