### ISSUE TITLE
Option to append a hash to injected URLs?

### ISSUE THREAD

**Issue by ansballard** [klei/gulp-inject#140]
I've been trying to clean up my gulp workflow for the past few weeks, and my gulp-inject code has boiled down to something like this:
```javascript
...
.pipe(inject(gulp.src(config.dist.js, {read: false}), {
        transform: function(filepath) {
          var hash = crypto.createHash("md5").update(fs.readFileSync(path.join(__dirname, "..", filepath))).digest("hex");
          var fp = filepath.split("/");
          return "<script type=\"text/javascript\" src=\"dist/" + fp[fp.length - 1] + "?hash=" + hash + "\"></script>";
        }
...
```
It just uses the native `crypto` node module to build a hash, then returns the script tag with the hash appended. My question is whether this could be added in as an option, e.g. `.pipe(inject({appendHash: true}))` or something like that. Or whether the module should only worry about injecting default tags, and leave any transformation to the user.

**Comment by joakimbeng** [comment]
Use an existing plugin for that: [`gulp-hash`](https://www.npmjs.com/package/gulp-hash).

**Example:**

```javascript
var gulp = require('gulp');
var hash = require('gulp-hash');
var inject = require('gulp-inject');

gulp.task('default', function () {
  var opts = {
    algorithm: 'sha1',
    hashLength: 40,
    template: '<%= name %><%= ext %>?hash=<%= hash %>'
  };
  return gulp.src('index.html')
    .pipe(inject(gulp.src('src/*.js').pipe(hash(opts))))
    .pipe(gulp.dest('dist'));
});
```
