### ISSUE TITLE
Not injecting Bootstrap css anymore

### ISSUE THREAD

**Issue by pwnjack** [klei/gulp-inject#145]
After the last Bootstrap update gulp-inject is not injecting the Bootstrap css anymore.
This happens because they removed the css as a main file in bootstrap's bower.json as noted [here](https://github.com/twbs/bootstrap/issues/16663)

Actually they changed the spec to have:

    "main": [
        "less/bootstrap.less",
        "dist/js/bootstrap.js"
      ] 

From this:

    "main": [
        "less/bootstrap.less",
        "dist/css/bootstrap.css",
        "dist/js/bootstrap.js",
        "dist/fonts/glyphicons-halflings-regular.eot",
        "dist/fonts/glyphicons-halflings-regular.svg",
        "dist/fonts/glyphicons-halflings-regular.ttf",
        "dist/fonts/glyphicons-halflings-regular.woff"
    ]

I know i can override the main property in my project's bower.json, just wanted to point this out, maybe you can find a solution to automate this and make it work again as it smoothly did until this bootstrap update.

**Comment by joakimbeng** [comment]
This is not up to `gulp-inject` to fix. It does not care what libraries you use, only what you pipe to it.
I think you should follow the conversation in the issue, and related, you posted to find a good solution for this.
