### ISSUE TITLE
Shouldn't the new JS and CSS files replace the old ones?

### ISSUE THREAD

**Issue by ericntd** [klei/gulp-inject#154]
After running the gulp task a few times, I ended up with multiple copies of my JS files and CSS files in my HTML template:
```html
<body>


    <div id="content" class="container-fluid wrapper">
    </div>

    <!-- inject:js -->
    <script src="/public/gen/prod/bundle-2038aaf2ae.js"></script>
    <script src="/public/gen/prod/bundle-a9895b7373.js"></script>
    <!-- endinject -->
</body>
```

**Comment by joakimbeng** [comment]
Please provide the code for how you're using `gulp-inject` to be able to help you better.

(just a hunch, but I think this could be caused by a caching plugin)

**Comment by ericntd** [comment]
Sorry I was using gulp-rev to generate multiple versions of my `bundle.js` script. So, it's not your fault to take all the scripts in my folders and inject them into the HTML file
