### ISSUE TITLE
relative flag creating file paths that unnecessarily go up to the parent folder

### ISSUE THREAD

**Issue by robianmcd** [klei/gulp-inject#160]
if my files are structured like this

```
gulpfile.js
public/
    index.html
    app.js
```

And I run the following gulp task

```
gulp.src('public/index.html')
    .pipe(inject(gulp.src('public/app.js'), {relative: true}));
```

Then I will get a script tag generated like this:
```
<script src="../public/app.js"></script>
```

Unfortunately my server can't handle going up (`..`) out of the public folder so this doesn't work. Ideally gulp-inject would create a script tag like this instead

```
<script src="app.js"></script>
```

I know I could just process all of my paths and manually make them relative to index.html but it would be nice if the `relative` flag in gulp-inject handled it.

Is there anyway to get inject working when you only have paths to files relative to your gulpfile? If not is this something that could be added? I'd be happy to look into creating a PR for this.

**Comment by ericsvendsen** [comment]
Instead of using the relative option, have you tried using the `ignorePath` and `addRootSlash` options?  Like so:

`gulp.src('public/index.html')`
&nbsp;&nbsp;&nbsp;&nbsp;`.pipe(inject(gulp.src('public/app.js'), {ignorePath: 'public', addRootSlash: false}));`

**Comment by robianmcd** [comment]
Ah didn't know about `ignorePath`. That did the trick. Thanks!

**Comment by dowsanjack** [comment]
This did do the trick, and I was able to sort out the problem. But, when I add this to 'watch' function, i'm still getting the same 'parent' folder. Have I done something wrong.

My watch task looks like this:
```
gulp.task('watch', function() {
  gulp.watch(paths.sass, ['sass']);
  gulp.watch(paths.bower, ['wiredep']);
  gulp.watch(paths.appScripts, {events: ['add', 'unlink']}, ['inject']);
});
```

and, my Inject task looks this way:
```
gulp.task('inject', function () {
  var target = gulp.src('./www/index.html');
  var sources = gulp.src(paths.appScripts, {read: false});

  return target
    .pipe($.plumber())
    .pipe(inject(sources, {
        ignorePath: '/www',
        addRootSlash: false
    )
    .pipe(gulp.dest('./www/'))
});
```
