### ISSUE TITLE
options.empty doesn't empty

### ISSUE THREAD

**Issue by randycasburn** [klei/gulp-inject#164]
UseCase: as part of a 'clean everything' strategy, I want to clean out my injections so I can restore my index.html file to its pristine state.

Steps to recreate: 

1. use gulp-inject to inject css & js in the most basic way
2. use gulp-inject with an empty stream
3. set {empty: true} as options
4. execute task

This is my gulp task:

gulp task: 

`gulp.task('clean-staged-links-from-index.html', function(){
    return gulp.src(injectTarget)
        .pipe(inject(gulp.src('EMPTY'),{empty: true}))
        .pipe(gulp.dest(srcDir));
});
`

**Comment by HichemBenChaaben** [comment]
if there's no files returned in the stream, it wont work

**Comment by randycasburn** [comment]
From the docs:
> When true all tags without corresponding files will be emptied.
So I've (1) tried by selecting a single file that does not exist in any tag (so all tags in file would be "without corresponding files"). The tags are not emptied.

I've also (2) tried the exact same glob pattern used with injecting the tag initially.

Then I tried (3) a string that returns no file list (example above).

What am I missing?

**Comment by HichemBenChaaben** [comment]
@randycasburn it's a bug, the empty option  and the transformer function are both working if the stream returned have files.

what should happen is if the stream returned is empty, it should remove the content of the inject tags

**Comment by randycasburn** [comment]
I do realize gulp-inject is doing this internally...but the exposed 'empty' API is not.

So will you be marking this as a bug? I found no open issues related to this. All related issues have been closed as if this feature works correctly.

**Comment by joakimbeng** [comment]
@randycasburn weird that you don't get it working!
There's already a [test that covers this use case](https://github.com/klei/gulp-inject/blob/e246aa8693689219292078aef70efc4202ec4812/src/inject/inject_test.js#L522-L529) but to be sure that it really works I've created a small repo which demonstrates how to use the `empty` option and that it works as you intend with empty streams: [testing-gulp-inject-empty](https://github.com/joakimbeng/testing-gulp-inject-empty).

Or am I missing something from your scenario?

**Comment by randycasburn** [comment]
Dang it!  turns out I was using a very old version of inject - as it turns out, the current version works as expected.

Sorry for the dust up.

<note to self: check the basics>

**Comment by joakimbeng** [comment]
@randycasburn no worries :)
