### ISSUE TITLE
Recommendation: Rename 'empty' add 'clearTags' API methods

### ISSUE THREAD

**Issue by randycasburn** [klei/gulp-inject#165]
1) rename 'empty' option to 'replaceExisting' or 'replaceCurrent'
2) create API option for selectively removing tags or removing all tags ('clearTags')

Rationale:

The documented purpose of the empty method is ambiguous. It seems the purpose (and the way it works) is to add tags for those files returned in a stream and remove tags for files NOT in the stream.

Some of us (yours truly) interpreted that as "if you pass an empty stream and use the empty option, then ALL tags will be removed for all inject:{{ext}}. **But the API is not designed to work in this manner.**

To overcome the ambiguity, recommend **renaming** the '**empty**' option to '**replaceExisting**' or '**replaceCurrent**';

There are several documented use cases for **selectively removing individual tags, groups of tags, and all tags**. There isn't currently a way to accomplish this. Recommend creating a new option (perhaps called '**clearTags**' that would remove tags for files matching the stream, or remove all tags if the stream is empty.

**Comment by sagarjs** [comment]
+1

**Comment by joakimbeng** [comment]
@randycasburn do you still think this is necessary given that #164 is closed?

**Comment by randycasburn** [comment]
No longer necessary
