### ISSUE TITLE
gulp-inject fails for readonly index.html

### ISSUE THREAD

**Issue by umeshv** [klei/gulp-inject#170]
The gulp-inject fails when we try to run it on read-only index.html file.

`events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EPERM, open 'C:\path\index.html'
:gulp_build FAILED`

Is there any options to ignore the file state?

**Comment by joakimbeng** [comment]
It appears that the `index.html` cannot even be opened by `gulp.src`, so this has nothing to do with this plugin. Or even if you succeed in opening the file but are trying to pipe it to the same destination (i.e. `C:\path\`) using `gulp.dest` this is still not an issue with this plugin.

This plugin does not read nor write files from/to the disk, `gulp` itself does that through `gulp.src` and `gulp.dest`.

I recommend you to either change the permissions on `index.html` or pipe to another destination where the current user have write access or file an issue in the `gulp` repository if you're unable to solve this.
