### ISSUE TITLE
SyntaxError: Unexpected token ,

### ISSUE THREAD

**Issue by toutpt** [klei/gulp-inject#171]
gulp-inject/src/inject/index.js:127
      startTag,
              ^
SyntaxError: Unexpected token ,
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (.../node_modules/gulp-inject/index.js:4:28)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

https://github.com/klei/gulp-inject/blob/master/src/inject/index.js#L127
corresponding commit (from the blame)
https://github.com/klei/gulp-inject/commit/852fe9dfd2e12a4e1a577bff42bd2f84d49b8cf8

**Comment by joakimbeng** [comment]
You're probably running an old NodeJS version. From gulp-inject v4 at least NodeJS v4 is required (as stated in the read me). Is this the case?

**Comment by toutpt** [comment]
Oh yes .... 
I didn't know the Enhanced Object Literals new feature from ES6.

Thank you !

**Comment by shyamal890** [comment]
Even after having NodeV4.4.3 installed, I am still facing this same issue. NOTE: Works alright with gulp-inject@3

**Comment by robajz** [comment]
Is there a way to update nodejs used by visualstudio?

**Comment by TrySound** [comment]
@joakimbeng Do you really drop out bunch of old machine users only for shorthand properties? I agree nobody need node 0.10, caz is doesn't have promises. But simplifying syntax in this case seems unregardful about users. You can use babel if you like so.

**Comment by Nelvision** [comment]
@robajz You can update the version per project by going to project root command line and run...
npm install gulp-inject@3.0.0

**Comment by TrySound** [comment]
@Nelvision I can. But what if will be found a bug? Will you support both majors?

**Comment by joakimbeng** [comment]
@TrySound what forces you to have an old Node version? If you're already on 0.12 the upgrade to v4 should be easy. The current LTS version of node is v4, so IMO that is the lowest version anyone should use today.
If gulp-inject can be a reason for people to upgrade their Node version I think that's a reason for not making gulp-inject compatible with Node <4. Otherwise we get stuck in a situation like the one with old browsers, those who don't autoupdate themselves, which I for one don't want.

**Comment by robajz** [comment]
If the node.js is that old, i'd agree to update. The strange thing is that only inject has this problem. So long as there's this old node version distributed by default with the dev tools (vs 2015), i think it would be courteous to support it. Either way I solved my problem without inject not to force the whole team into special casing it. We like things to work out of the box. Kind regards, rob

On April 28, 2016 9:00:10 AM CEST, Joakim Carlstein <notifications@github.com> wrote:
>@TrySound what forces you to have an old Node version? If you're
>already on 0.12 the upgrade to v4 should be easy. The current LTS
>version of node is v4, so IMO that is the lowest version anyone should
>use today.
>If gulp-inject can be a reason for people to upgrade their Node version
>I think that's a reason for not making gulp-inject compatible with Node
><4. Otherwise we get stuck in a situation like the one with old
>browsers, those who don't autoupdate themselves, which I for one don't
>want.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/klei/gulp-inject/issues/171#issuecomment-215328929

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by joakimbeng** [comment]
I'm convinced, I will make `gulp-inject` compatible with NodeJS <4 again.

**Comment by toutpt** [comment]
this is needed. easy to achieve but more and more gulp out their use es6 and that is up to the maintainers to choose. 

look at node 4 and You Will update your stuff to this version. this is more important (sécurité+feature) than compatibilité.

and there is no problem to update from 0.10. to 4 which is the curren lts.

**Comment by joakimbeng** [comment]
@toutpt I agree with you. But to save myself some time I'm fixing this now. I will reconsider breaking compatibility with Node <4 again when [statistics like this looks different](https://twitter.com/seldo/status/726164925425426433)
