### ISSUE TITLE
No release notes 

### ISSUE THREAD

**Issue by danielmariz** [klei/gulp-inject#174]
I've tried to update from v3.0.0 to v4 but I'm having lots of errors and I can't find a way to fix it.
So not sure what I have to change in my tasks to make it works with new version.

**Comment by joakimbeng** [comment]
Fixed release notes now: [v4.0.0](https://github.com/klei/gulp-inject/releases/tag/v4.0.0)

It's probably because your on a NodeJS version below v4?

**Comment by danielmariz** [comment]
Yes sure I wasn't,
thanks
