### ISSUE TITLE
removeTags removes line breaks

### ISSUE THREAD

**Issue by anvish** [klei/gulp-inject#177]
Setting removeTags: true causes removal of line breaks between imported `<script>` tags
```
    <!-- inject:js -->
    <!-- endinject -->
```
leads to
`    <script src="js/main.min.js"></script><script src="js/_ts.min.js"></script>`

**Comment by jmight** [comment]
I just noticed this after doing a fresh upgrade to Gulp 4.

Commenting out the following line in node_modules/gulp-inject/src/inject/index.js makes it work again:

`// startTag.lastIndex -= startMatch[0].length;`

I ran a test with and without that line commented and then diff'd the output of the two files.  The only difference was the line breaks between `<script>` and `<link rel="stylesheet">` tags.

Don't have the time to comb through the entire gulp-inject source to see if there will be any negative side affects of commenting out the line, but there don't appear to be any.
