### ISSUE TITLE
Empty a <!-- inject: -->

### ISSUE THREAD

**Issue by Davidx7** [klei/gulp-inject#178]
How do we empty an inject tag ? 
That would be very useful

I want
```
<!-- inject:dev:css -->
<script ... />
<!-- endinject -->
````
to become 
```
<!-- inject:dev:css -->
<!-- endinject -->
````
or even delete completely. 

I don't want to read or write to it, I just to empty it. 
Is that possible?

**Comment by joakimbeng** [comment]
There's an [`empty` option](https://github.com/klei/gulp-inject#optionsempty) for that. Please try that and reopen the issue if it doesn't help.
