### ISSUE TITLE
Inject a CDN URL

### ISSUE THREAD

**Issue by brianmhunt** [klei/gulp-inject#18]
It is not immediately clear how one would inject a url for a CDN?

E.g. how might one inject the following:

```
["http://cdnjs.cloudflare.com/ajax/libs/jasmine/1.3.1/jasmine.js", "./spec/test"]
```

It would appear that `gulp.src()` ignores the URL, and I did not see any unit tests corresponding with this functionality.

Many thanks for any thoughts. Cheers.

**Comment by eloone** [comment]
What if we want to inject `http://localhost:35729/livereload.js` (for example) only for the development build?

**Comment by joakimbeng** [comment]
@eloone use [`gulp-embedlr`](https://www.npmjs.com/package/gulp-embedlr) for that.

**Comment by eloone** [comment]
Thanks @joakimbeng. In the end I did it like this:
```
indexStream
      .pipe(inject(gulp.src(''), {
      starttag: '<!-- livereload -->',
      transform: function(){
        return '<script src="http://localhost:35729/livereload.js"></script>';
      },
      empty: true
      }));
````
And in index file:

````
<!-- livereload -->
<!-- endinject -->
````

It does the job without a new module, it's what I wanted.

**Comment by joakimbeng** [comment]
Great!

I don't understand your attitude against another module though... What's wrong with a module which already exists and does exactly what you want in fewer lines of code? It goes against the whole Gulp and Node philosophy...

**Comment by eloone** [comment]
@joakimbeng I don't have anything against modules. It's just that what I want is so simple, I don't think I should use another module for that and clutter my stack with it. I think this is something the `gulp-inject` module should be capable of if we stick to its purpose of "injecting" a file with content, at least that's what I expect from it when I use it to build my index file.

**Comment by johnwoolee** [comment]
I ended up using `gulp-replace` for a similar use case:

html:
`<!-- replace:google-places -->`

gulp:
```
return gulp.src(path.join(conf.paths.src, '/*.html'))
    .pipe($.inject(injectStyles, injectOptions))
    .pipe($.inject(injectScripts, injectOptions))
    .pipe($.replace('<!-- replace:google-places -->', replacePlaces))  // <-- gulp-replace
    .pipe(wiredep(_.extend({}, conf.wiredep)))
    .pipe(gulp.dest(path.join(conf.paths.tmp, '/serve')));
```

replacePlaces:
```
const replacePlaces = match => {
    switch (process.env.NODE_ENV){
      case 'dev':
        return '<script src="https://maps.googleapis.com/maps/api/js....."></script>';
      case 'production':
        return '<script src="https://maps.googleapis.com/maps/api/js......"></script>';
      default:
        return match;
    }
  }
```
