### ISSUE TITLE
Plural State of logged message on injected files.

### ISSUE THREAD

**Issue by johnkariuki** [klei/gulp-inject#192]
Currently, the logged message on the number of injected files is statically set to plural state.

<img width="415" alt="screen shot 2016-07-21 at 2 45 46 pm" src="https://cloud.githubusercontent.com/assets/16223627/17021625/dd8c0710-4f51-11e6-9a66-2d67a6033b71.png">

It would make sense to have the message reflect the correct plural state of the `filesCount` variable.

``` js
   if (filesCount) {
      var pluralState = filesCount > 1 ? 's' : '';
      log(cyan(filesCount) + ' file' + pluralState + ' into ' + magenta(target.relative) + '.');
    } else {
      log('Nothing to inject into ' + magenta(target.relative) + '.');
    }
```

This would look something like this.

<img width="410" alt="screen shot 2016-07-21 at 2 47 34 pm" src="https://cloud.githubusercontent.com/assets/16223627/17021670/2a94736c-4f52-11e6-9e90-041921ed7b6b.png">

**Comment by joakimbeng** [comment]
Closed by #193
