### ISSUE TITLE
Inject script content into <head>

### ISSUE THREAD

**Issue by ganlanyuan** [klei/gulp-inject#199]
Hey, thanks for your awesome work!
How can I inject script content directly into `<head>` tag, since 

```
<!-- inject:js -->
<!-- endinject -->
```

is not valid inside `<script>` tag?
Same with css contents. How can I inject css code right into the `<style>` tags inside `<head>`?
Thanks

**Comment by ganlanyuan** [comment]
My current solution is
```javascript
gulp.src('part/head.php')
  .pipe(inject(loadcss, {
    name: 'loadcss',
    transform: function (filePath, file) {
      return '<script>' + file.contents.toString() + '</script>';
    }
  }))
  .pipe(gulp.dest('part'));
```
But if you can give some options like `starttag: '/* loadcss */'` with end tag `'/* endinject */'`, which are valid in both `<script>` and `<style>` tags, it will be much more convenient.

**Comment by joakimbeng** [comment]
Sorry but have you even read the readme?
For instance take a look at the [`starttag` option](https://github.com/klei/gulp-inject#optionsstarttag).

**Comment by ganlanyuan** [comment]
So what should I do if I want to inject *script code* into **php** file.

I tried this way:
**php**
```
<style>
	/* critical:css */
	/* endinject */
</style>
```
**gulpfile**
```
.pipe(inject(critical, {
  name: 'critical',
  transform: fileContents
}))
```
and
```
.pipe(inject(critical, {
  starttag: '/* critical:css */',
  transform: fileContents
}))
```

But it didn't inject anything. Is there anything wrong?

**Comment by ansballard** [comment]
You're injecting into an html file, so the library assumes your start and end tags will be html comments. You've specified a start tag, but not an end tag, so that's probably the issue.
```js
// ...
{
  starttag: '/* critical:css */',
  endtag: '/* endinject */'
  // ...
}
// ...
```

**Comment by ganlanyuan** [comment]
@ansballard Thanks a lot! 
It works now.
