### ISSUE TITLE
ng-href instead of href

### ISSUE THREAD

**Issue by aboalwi** [klei/gulp-inject#202]
How can i write ng-href instead of href
it's needed to support rtl languages and switch to the right css dynamically

the final result should be like this:

`<link rel="stylesheet" ng-href="css/rtl/style{{isRTL ? '_rtl' : ''}}.css">`

**Comment by joakimbeng** [comment]
Hello! This is possible using the `transform` option, see [this example](https://github.com/klei/gulp-inject#injecting-with-custom-transform-function-with-default-fallback) for instance
