### ISSUE TITLE
Ghost Bug!

### ISSUE THREAD

**Issue by stormbytes** [klei/gulp-inject#204]
I've got 2 arrays containing URLs and 2 identical tasks. The first task uses array set 1, and works fine.
The second task uses array set 2 and does not work!

Is there some secret gulp-inject bug I'm not seeing?

Full commented gulpfile.js here:

https://gist.github.com/3ac8e6f0fefd6bdc5658b9316be958f1

**Comment by develmts** [comment]
Maybe you missed  the "**return gulp. ...**" in the second case?
