### ISSUE TITLE
Strips tag declaration after processing 

### ISSUE THREAD

**Issue by mitchrenton** [klei/gulp-inject#209]
Hi.

We have different base URLs for our environments and therefore prepend the assets with the dynamic URL, problem is, the PHP gets stripped, is there a way to prevent this?

So our inject goes from this

```
<!-- inject:js -->
<script src="<?php echo $config['base_url']; ?>/assets/javascript/boolean/app.boolean.js"></script>
<!-- endinject -->
```

to this...

```
<!-- inject:js -->
<script src="/assets/javascript/boolean/app-0308673a34.boolean.min.js"></script>
<!-- endinject -->
```

**Comment by joakimbeng** [comment]
You can use the [`addPrefix`](https://github.com/klei/gulp-inject#optionsaddprefix) option

```javascript
gulp.src('index.php')
  .pipe(inject(gulp.src('path/*.js', {read: false}), {
    addPrefix: '<?php echo $config['base_url']; ?>'
  }))
  .pipe(gulp.dest('dest/'));
```

**Comment by mitchrenton** [comment]
Hi Joakim,

Thanks for getting back to me. I'm almost there!

The problem is I can't escape the ? in the JavaScript string...

```
addPrefix: '<\\?php echo $config[\'base_url\']; \\?>',
```

I'm no JavaScript expert but everywhere I've read seems to suggest that double forward slashes ``\\`` should escape a question mark.

Any ideas?
