### ISSUE TITLE
Add quiet option to documentation

### ISSUE THREAD

**Issue by Hativ** [klei/gulp-inject#221]
**Edit:** The quiet option is not documented, so this was a feature request first.

-----
I would like to have an option to disable output like
> gulp-inject 14 files into index.html.

**Comment by rejas** [comment]
Fixed by https://github.com/klei/gulp-inject/commit/8f2d6e555b6c626c56ba2e5fc8363aef67acfe0f#diff-04c6e90faac2675aa89e2176d2eec7d8
