### ISSUE TITLE
[Error] When empty is true, replace endTag by startTag

### ISSUE THREAD

**Issue by 11joselu** [klei/gulp-inject#224]
[See #L147](https://github.com/klei/gulp-inject/blob/master/src/inject/index.js#L147)

Code example (inyecting into jsp file): 

``` javascript
pipe($.inject(src(file), {
        relative: true,
        empty: true,
        starttag: '<%-- analytics:{{ext}} --%>',
        endtag: '<%-- endanalytics --%>'
      }))
```

**Comment by slhenty** [comment]
I have the same problem... and I've discovered where the bug is (line 147 in https://github.com/klei/gulp-inject/blob/master/src/inject/index.js)

Currently is:
```
    var endTag = getTagRegExp(opt.tags.end(targetExt, ext, opt.starttag), ext, opt);
```
Should be:
```
    var endTag = getTagRegExp(opt.tags.end(targetExt, ext, opt.endtag), ext, opt);
```

I'm planning to start the fix and submit a PR, ASAP.
