### ISSUE TITLE
js type="modules"

### ISSUE THREAD

**Issue by ThomasBrierley** [klei/gulp-inject#229]
Hi @joakimbeng I've written a little transform for automatically adding `type="module"` for script tags when the content includes the new ES6 import/export statements.

Would you be interested in including it as the default script transform? I ask first because it's more costly in that it must do some regex on the file source instead of just using the path name.

**Comment by ThomasBrierley** [comment]
Nevermind

**Comment by XShep** [comment]
@ThomasBrierley Hello, i know that it was long time ago, but how did you solve the problem? I have some JS files which have "import" statements. I'm trying to find any solution to inject those files with module type.
