### ISSUE TITLE
Can't remove beginning of injected path using 'IgnorePath'

### ISSUE THREAD

**Issue by mikecfisher** [klei/gulp-inject#28]
I'm trying to have gulp-inject, inject a bunch of JS files in my app. 

My folder structure looks like this

```
gulpfile.js
app/
    scripts/
    index.html
```

The file comments that get injected look like this. 
`<script src="/app/scripts/app.js"></script>`

However I need to remove the /app/ so the index.html file loads the .js files properly. 
I've tried adding this  `{ignorePath: 'app'}` but it doesn't seem to remove it from the inject comments. 

Any ideas?

**Comment by deveshk** [comment]
Not working with any of options . 
gulp.task('index', function () {
    log("Injecting js and css to index.html");
    log(__dirname);
   return gulp.src(dest+'index.html')
        .pipe(plugins.inject(gulp.src([dest+'js/*.js',dest+'css/*.css'], {read: false, addRootSlash: false})
        .pipe(plugins.angularFilesort())), {ignorePath: 'clients/app', relative: true})
        .pipe(gulp.dest(dest));

});
Please suggest

**Comment by Camusensei** [comment]
Hello.

1) Define "Not working"
2) Please indent your code
3) addRootSlash: false is an option for plugins.inject, not gulp.src
4) Please show us your file tree

Regards,
Camusensei

**Comment by joakimbeng** [comment]
@Camusensei :+1:

**Comment by digitalinfamy** [comment]
I came across the same issue and the new relative option worked really well for me.  Just in case anybody else is stuck...

I'm using ionic and have a folder structure
gulpfile.js
    /www/index.html
    /www/js/all.js

config has
        app: './www/',
        index: app + 'index.html'
        js: [ 
            app+'js/**/*.module.js',
            app+'js/**/*.js'
        ],
        styles: [
            app+'.css/**/*.css'
        ]
the gulp task then contains
    return gulp
        .src(config.index)
        .pipe($.inject(gulp.src(config.js), {read: false, relative: true}))
        .pipe($.inject(gulp.src(config.styles), {read: false, relative: true}))
        .pipe(gulp.dest(config.app));

**Comment by joakimbeng** [comment]
@digitalinfamy great! A note though, `gulp-inject` does not have a `read` option ;) It should be inside the `gulp.src`.

**Comment by slopesidecreative** [comment]
the only method that works for me is the one suggested by <b>r4fx</b>

**Comment by frisellcpl** [comment]
Although trying all of the examples above I still cant get this to work.

My scenario is quite basic, perform tasks based on a folder structure in the source code. Inject the script and style tags based on server POV. Hence I would like to remove src from the path when `injecting.`

The following code doesnt work. Have tried with various changes in working directory as well. Any clues of what might be wrong? To me it seems like inject() gives a s***t about ignorePath: 'src'. :)(?)

`
var rootCshtmlDir = './Garant/Views/Shared/';                                                 
var scssTargetDir = './Garant/static/sass/';                                                  
var cssOutputDir = './Garant/static/stylesheets/';                                            
var scriptDir = './Garant/static/scripts/';                                                   
                                                                                              
gulp.task('default', ['minify', 'uglify'], function() {                                       
  var sources = gulp.src([cssOutputDir + '*.min.css', scriptDir + '*.min.js'],                
                          {read: false});                                                     
                                                                                              
  gulp.src(rootCshtmlDir + '_Root.cshtml')                                                    
    .pipe(print())                                                                            
    .pipe(inject(sources, {                                                                   
      ignorePath: 'Garant',                                                                   
      addRootSlash: false,                                                                    
      relative: false}))                                                                      
    .pipe(gulp.dest(rootCshtmlDir));                                                          
});
`

**Comment by Camusensei** [comment]
Hi. Sorry, this is not going to be the answer you expect.

Instead of trying out the examples you see, please READ everything.
By the time I was still active on this (I have completely stopped UI dev by now), I explained that gulp.src had a VERY BIG IMPACT on what gulp.inject was able to ignore or not.
The things may have changed now that @joakimbeng  [Clarifyined injected paths](https://github.com/klei/gulp-inject/wiki/Clarifying-injected-paths) so I can't help anymore.

But I can notice that you are ignoring 'src' when you are sourcing './src' so that may be an issue in your case.
You also don't tell us what you get and what your expectect result is!

If you really want help, you're going to have to try a bit harder.

Regards,
Camusensei

**Comment by frisellcpl** [comment]
Thanks for your reply.

Sorry if I upset you @Camusensei . This was not the intended purpose of my post. Of coarse I read the posts, not solely tested them. However I have no possiblity to change the folder structure. I will keep trying, I'm certain that I've just missed something. I'll also have a look on the post from Joakim.

Thanks for your help and good luck with your non-UI-dev.

**Comment by Camusensei** [comment]
Changing the folder structure is really like a last-chance scenario, everything is always possible with gulp.inject, it's just a matter of understanding correcltly how it work.
If you provide us with the correct information of what you want, we can even try out things locally for you to give you a definitive answer to your problem! But we need precise information for that, that's why I alway tell people to give us their file tree, gulp code and expected results :)
And *please* don't take my bad mood personally!

**Comment by frisellcpl** [comment]
Hi,

I managed to achieve my goal.

Below is the final code. However I still dont really see what didnt work with my former code (the .src/ and src was tested in both "directions"). Probably just finally got the right combination of settings ;)

**Tree** 

* gulpfile.js
  * src/static/stylesheets/
  * src/static/scripts/
  * src/Views/Shared/

**Code**

```javascript
var rootCshtmlDir = 'src/Views/Shared/';                                                   
var scssTargetDir = 'src/static/sass/';                                                    
var cssOutputDir = 'src/static/stylesheets/';                                              
var scriptDir = 'src/static/scripts/';                                                     
                                                                                              
gulp.task('default', ['minify', 'uglify'], function() {                                       
    var sources = gulp.src([cssOutputDir + '*.min.css', scriptDir + '*.min.js']);             
                                                                                              
    gulp.src(rootCshtmlDir + '_Root.cshtml')                                                  
        .pipe(inject(sources, {ignorePath: 'src'}))                                        
        .pipe(gulp.dest(rootCshtmlDir));                                                      
});
```

**Output**

```html
<link rel="stylesheet" href="/static/stylesheets/GTebo.main.min.css">
<script src="/static/scripts/305n2c.app.min.js"></script>
```

_Pleaase note that "src" is a rewrite of the original project name._

**Comment by Camusensei** [comment]
Great news! And thank you for the final code :)

**Comment by adriennn** [comment]
hi, 
came across a similar problem. Figured out it was a typo (two) in the [docs](https://github.com/klei/gulp-inject/wiki/Clarifying-injected-paths#2-using-gulp-injects-relative-option):

this block is missing a `)` so if you copy from the examples, gulp will build without showing any error:

```javascript
gulp.src('./src/index.html')
  .pipe(inject(gulp.src('./src/**/*.js', {read: false}), {ignorePath: 'src'})
  .pipe(gulp.dest('./dist'));
```

should be:

```javascript
gulp.src('./src/index.html')
  .pipe(inject(gulp.src('./src/**/*.js', {read: false}), {ignorePath: 'src'}))
  .pipe(gulp.dest('./dist'));
```

here is a working example:

```javascript
 .pipe(inject(gulp.src('./dist/libs.min.js', {read: false}), 
    {starttag: '<!-- inject:head:js -->', ignorePath: 'dist', addRootSlash: false}))
```

**Comment by twxia** [comment]
Have similar issue here:
when I set the options: `relative`
I need to set ignorePath like this:  `ignorePath: ['../dist', '../']`
to let `dist/zh-tw/index.html` has a correct path 
here's my structure: 
```
dist/
├── assets
│   ├── scripts
│   │   └── index.min.js
│   └── styles
│       └── index.min.css
├── index.html
└── zh-tw
    └── index.html
```

**Comment by Camusensei** [comment]
Hello twxia,

Nobody will help you here, please open **another issue** and be **more descriptive** about your issue.

Regards,
Camusensei

**Comment by vittal288** [comment]
```
gulp.src('./index.html')
  .pipe(inject(gulp.src('lib/**/*.js',{cwd: 'dist/'}, {read: false}), {name: 'libs'},{relative: false}))
  .pipe(inject(gulp.src('scripts/**/*.js',{cwd: 'dist/'}, {read: false}), {name: 'customScripts'},{relative: false}))  
  .pipe(gulp.dest('./dist'));
```

Have added CWD object as current target directory name and removed "dist" from source file

**Comment by jpduckwo** [comment]
`ignorePath: 'x'`
and...
`addRootSlash: false `
solved my issues with this, thanks

**Comment by FatimahSanni** [comment]
@adriennn Thanks a bunch man! was running mad already lol.

**Comment by grimpa** [comment]
This works for me:

var paths = {
    html: ['doc/_src/**/*.html', '!doc/_src/_partials/*.html'],
    scripts: 'doc/js/**/*.js',
    styles: 'doc/styles/css/*.css',
    out: 'doc/'
};

gulp.task('inject', function () {
    gulp.src(paths.html)
        .pipe(inject(gulp.src([paths.styles], {read: false}),
            // Options
            {
                ignorePath: 'doc',
                addRootSlash: false
            }
        ))
        .pipe(gulp.dest(paths.out));
});
