### ISSUE TITLE
Option to remove inject comments

### ISSUE THREAD

**Issue by ppvg** [klei/gulp-inject#36]
Suggested enhancement: an option to remove the `inject` / `endinject` comment pair after injection of the source tags. The `endinject` comment could be optional if this option is set.

**Comment by AdamBuczynski** [comment]
+1 for this
@drewnoakes , did you look into creating a PR for this?

**Comment by AdamBuczynski** [comment]
I resorted to using these two simple gulp plugins to remove comments, because HTML minifiers would introduce other issues that were a problem with my Angular templates:

https://www.npmjs.com/package/gulp-remove-html-comments
https://www.npmjs.com/package/gulp-remove-empty-lines
