### ISSUE TITLE
Inject:scss - Is there a way to inject files into a scss file? 

### ISSUE THREAD

**Issue by jgatjens** [klei/gulp-inject#49]
var sources = gulp.src(['app/pages/*_/_.scss']);
var target = gulp.src('app/styles/main.scss');

return target.pipe(inject(sources, {starttag: '// '}))
    .pipe(gulp.dest('./app'));

main.scss
// 
//

**Comment by Cenlins** [comment]
it doesn't work for me

`gulp.task('injectSass', function() {
    var target = gulp.src('components/sass/style_ltr.scss');
    // It's not necessary to read the files (will speed up things), we're only after their paths:
    var sources = gulp.src(['components/sass/injectTest/*.scss'], { read: false });


    return target.pipe(inject(sources, {
            starttag: '// inject:{{ext}}',
            endtag: '// endinject',
            transform: function(filepath) {
                return '@import(' + filepath + ');';
            }
        }))
        .pipe(gulp.dest('components/sass/'));

});`
