### ISSUE TITLE
addRootSlash not working with cwd?

### ISSUE THREAD

**Issue by mgcrea** [klei/gulp-inject#55]
I'm trying to drop the rootSlash from the output (needed to run on mobile devices).

Tried:

``` js
var src = {
  cwd: 'app',
  scripts: '{,modules/*/}scripts/**/*.js'
};

// [...]

.pipe(inject(gulp.src(src.scripts, {cwd: src.cwd, base: src.cwd}, {addRootSlash: false}).pipe(angularFilesort())))
```

But I end up with a rootSlash anyway, on an `index.jade` file.

Tried `addPrefix: '.',` as a workaround, but it's not working.

**Comment by ingo777** [comment]
It seems that you are using the `cwd`, `base` and `addRootSlash` options in the `gulp.src()` call instead of in the `inject()` call. Or am I wrong?
