### ISSUE TITLE
Doesn't remove injections when stream is empty

### ISSUE THREAD

**Issue by gruppjo** [klei/gulp-inject#59]
Hi,
I'm using gulp-inject to inject some files `./app/scripts/**/*.js` into my index.html. When gulp finds files, the plugin works as expected and injects all files. But when I remove all files from the filesystem the files aren't removed in the index.html. I experimented a little bit and found out that when at least one file is in the stream the plugin correctly removes all others. When I remove the last file, the index.html remains untouched resulting in 404's.

I reduced the problem to this simple task to reproduce it:

```
gulp.task('inject', function () {
  var jsFiles = gulp.src(['./app/scripts/**/*.js']);

  return gulp.src('./app/index.html')
    .pipe($.inject(jsFiles, {relative: true}))
    .pipe(gulp.dest('./app'));
});
```

Am I doing something wrong or is this the intended behavior?

**Comment by gruppjo** [comment]
The following scenario: I'm building mobile apps with cordova. Cordova provides a `cordova.js` file which needs to be injected per platform (ios, android, etc...). When developing the app in the browser, no `cordova.js` file should be injected. Thus I have two injection blocks in my `index.html`
```
<!-- build:js scripts/vendor.js -->
<!-- inject:cordova:js --> 
<!-- endinject -->
<!-- bower:js -->
<!-- endbower -->
<!-- endbuild -->

<!-- build:js scripts/app.js -->
<!-- inject:js -->
<!-- endinject -->
<!-- endbuild -->
```
First block injects `cordova.js` and allo bower components and builds them into `vendor.js`.
Second block injects all application js files.

When running `gulp build --target=ios` the injection task is designed to run
```
gulp.src('./app/index.html')
    .pipe($.inject(cordovaFile, {starttag: '<!-- inject:cordova:{{ext}} -->', relative: true}))
    .pipe(gulp.dest('./app'));
```
and inject the `cordova.js`.

When I run `gulp watch` the `cordova.js` should to be removed, since it's not available on the desktop. I figured this could established by just providing an empty stream. However this doesn't work. So after every build I get a `404 `for the `cordova.js` when running `gulp watch`. Additionally I need to be careful to not check in the `cordova.js` in my git repository.

Does this help?

**Comment by johnpapa** [comment]
I've also got a scenario where I want to inject a section of files only if a argument is passed to gulp. If that arg is missing , i want the inject block to be emptied. I'm working around it with a hack right now, but it would be nice to have an option to remove files if its an empty stream.

**Comment by kurdin** [comment]
>I've also got a scenario where I want to inject a section of files only if a argument is passed to gulp. If that arg is missing , i want the inject block to be emptied. I'm working around it with a hack right now, but it would be nice to have an option to remove files if its an empty stream.

+1, this would be very nice if we can remove/empty injected block with option like ``emptyTag : true``

**Comment by kurdin** [comment]
in case if anybody need workaround, here is how I remove scripts with gulp-replace

```Javascript
var replace = require('gulp-replace');
...
gulp.task('remove-dev-js', function() {
  return gulp.src('./html/**/*.html')
  	.pipe(replace(/<!-- (.*?):js -->([\S\s]*?)<!-- endinject -->/gmi, '<!-- $1:js -->\n<!-- endinject -->'))
  	.pipe(gulp.dest('./html'));
});
````

**Comment by derekgreer** [comment]
I submit that a build-in solution is definitely needed.  Perhaps an options can be added that allows for specifying a common prefix and a removeTags flag for removing the tags marked with a prefix prior to injection.

**Comment by derekgreer** [comment]
The desire to remove sections probably arises for many where style sheets or scripts need to be injected in a particular order for local/debug builds and as combined/minifed for release builds.  For example:

```
<!-- bower:js -->
<!-- endinject -->

<!-- otherThirdParty:js -->
<!-- endinject -->

<!-- myStuff:js -->
<script src="~/dist/lib/how-it-be-in-prod-9cebad55e4.js"></script>
<!-- endinject -->
```


For such cases, another workaround to consider is to use a single injection tag for all script types and combine multiple streams into one stream which is passed to inject.  This will also allow you to conditionally combine streams based upon environment variables, etc.  The best library I've found for doing this is streamqueue.

Here's an example:
```
gulp.task("inject-dependencies", function() {
  var layoutStream = gulp.src("./index.html", { base: "./" });

  var firstStream = gulp.src("something/**/*", { read: false });
  var secondStream = gulp.src("something/**/*", { read: false });
  var thirdStream = gulp.src("something/**/*", { read: false });

  var stream = isRelease ? firstStream : queue({ objectMode: true }, secondStream, thirdStream);

  return layoutStream
    .pipe($.inject(stream, {
      name: "scripts",
      relative: false,
      addRootSlash: false
    }))
    .pipe(gulp.dest("./"));
});
```
