### ISSUE TITLE
Unable to inject js and css !

### ISSUE THREAD

**Issue by abdulwahid24** [klei/gulp-inject#66]
Hi, 

I tired this but its not working.

      gulp.src('src/*.html')
       .pipe($.inject(gulp.src('dist/assets/js/*.js')), {
          read: false,
          starttag: '',
          addRootSlash: false,
          addPrefix: '../'
       }))'

    .pipe($.inject(gulp.src('dist/assets/css/*.css'),{
       read:false,
       starttag: ''
     }))`

I am unable to see these tags into my index.html

**Comment by MikaAK** [comment]
Are you using jade or a templating language? You should check what the comments actually get output as as in jade its output like `<!-- inject..-->` as opposed to `<!-- inject.. -->`.

**Comment by Camusensei** [comment]
I vote for closing this as a non-issue.

**Comment by MikaAK** [comment]
+1
