### ISSUE TITLE
Option to reduce log messages

### ISSUE THREAD

**Issue by Arkkimaagi** [klei/gulp-inject#76]
I do not want extra log messages unless there is a problem. Other gulp plugins seem to follow this rule but gulp-inject always wants to tell that it did something like:
```
[19:16:13] gulp-inject 1 files into signin/checkLogin.html.
```
I really do not care to know this unless I'm debugging gulp-inject.

Could these messages be optional with an setting in the options?

**Comment by ryanfields** [comment]
I have an alternate use case where I do want to see these messages, but only if something was injected.  I've got a project where a large number of files may or may not include injection points.  It's confusing to see "gulp-inject X files into Y" for a ton of files which were candidates for injection but in which no actual injection occurred.

**Comment by hans-d** [comment]
+1

**Comment by akullpp** [comment]
+1

**Comment by ryeballar** [comment]
+1

**Comment by ptarjan** [comment]
+1

**Comment by joakimbeng** [comment]
Now there's a `quiet` option (see #105 ) which does this.
