### ISSUE TITLE
Inject breaks with array call at top of file

### ISSUE THREAD

**Issue by MikaAK** [klei/gulp-inject#78]
I've been playing around with gulp-inject recently and for some reason the following code will throw the error `Cannot call method 'map' of undefined`.

If you omit the `angular.module` call it will not crash, or if you inline the dependencies it will not crash either. The issue here is I need the dependencies to be a variable.
Another case it breaks is on `[]` calls. For example `[].slice.call(this)` will cause gulp to crash.

```javascript
'use strict'

var dependancies = ['lbServices', 'edvisor.api.student']

angular.module('app', dependancies)
```

**Comment by joakimbeng** [comment]
@MikaAK I don't think this is an issue with `gulp-inject`but instead `gulp-angular-filesort`. Please verify and file an issue there instead..

**Comment by topherfangio** [comment]
For future visitors, there is a bug report here with no updates: https://github.com/klei/gulp-angular-filesort/issues/24
