### ISSUE TITLE
Question on `collectFilesToInject` function

### ISSUE THREAD

**Issue by dman777** [klei/gulp-inject#79]
I was studying your code for learning purposes. In `collectFilesToInject`, why do you use `process.nextTick` in:

```javascript
  function resolve (cb) {
    process.nextTick(function () {
      cb(collection);
    });
  }
```

I ask this because with `while (queue.length) { resolve(queue.shift()); } `, it will throw these non blocking jobs on the Queue and each one will run async since I/O operations are natively non-blocking, This would be done without `process.nextTick()`. However, since we are using `process.nextTick()`...which is blocking(in contrast to `setImmediate()`), doesn't this defeat async nature?

**Comment by joakimbeng** [comment]
@dman777 I see. I guess I haven't read enough about those functions to understand the difference between them. Now when I have, I agree with you that `setImmediate()` should be used instead.
