### ISSUE TITLE
Inject into .js file

### ISSUE THREAD

**Issue by websirnik** [klei/gulp-inject#81]
I'm trying to inject a js dependency into a .js file, so I could lazy load that file later. In my Angular use case it looks like this:
```javascript
// analytics-module.js that is later get concatinated to app.js
$ocLazyLoad.load({
    name: 'angles',
    files: ['<!-- inject:analytics:js --><!-- endinject -->']
}).then(function() {
    // Show analytics
});
```
Im trying to achive it with the following task:
```javascript
// gulpfile.js
gulp.src('_public/js/app*.js')
.pipe(inject(gulp.src(["_public/js/vendor-analytics*.js"], { read: false }), {
    ignorePath: '/_public/',
    starttag: '<!-- inject:analytics:js -->',
    transform: function (filepath, file, i, length) {
        return filepath;
    }
}))
.pipe(gulp.dest("_public/"));
```

I'm getting the following output: `gulp-inject 1 files into app.js.`, but in reality the placeholder for the file does not get changed to the filepath.

Does injection into .js files is supported? In there a way to debug it somehow?

**Comment by joakimbeng** [comment]
@websirnik yes injection into `.js` is supported, it should use the `html` injection tags by default.

I don't see why it shouldn't work. But your destination path is only `_public` so the results would be written to `_public/app.js` have you checked that file?

I'm afraid the debugging possibilities are quite limited, you can always edit the module source though, and reinstall it when you want to reset it.

**Comment by websirnik** [comment]
Got it. Kinda worked. The destination should have been `gulp.dest("_public/js")` for me.

But here is another thing. It gets pasted as:
```javascript
$ocLazyLoad.load({
    name: 'angles',
    files: ['<!-- inject:analytics:js -->/js/vendor-analytics.js<!-- endinject -->']
})
```

Is there a way to get rid of the placeholder tags?

**Comment by joakimbeng** [comment]
I'm afraid that's not possible, see #59 .

In your case maybe this can work:

```javascript
gulp.src('_public/js/app*.js')
.pipe(inject(gulp.src(["_public/js/vendor-analytics*.js"], { read: false }), {
    ignorePath: '/_public/',
    starttag: '/* inject:analytics */ files: [',
    endtag: ']',
    transform: function (filepath, file, i, length) {
        return '\'' + filepath + '\'' + (i + 1 < length ? ', ' : '');
    }
}))
.pipe(gulp.dest("_public/js"));

// and:

$ocLazyLoad.load({
    name: 'angles',
    /* inject:analytics */ files: []
})
```

Then your files will be injected into the files array, and even comma separate the files if there's more than one file.

**Comment by jmls** [comment]
I am trying to achieve something similar, but failing miserably

In my case, I want to inject some json data into a js file

so, I have a service file called **myservice.js**

```javascript
(function() {
  angular
      .module('myModule')
      .service('myService',myService);
       /** @ngInject */
     function myService() {
        return
          /* inject:json */
          /* endinject */
    }
})()
```

I have a **data.json** file in the same directory

and I have this inject statement

```javascript
gulp.task('injectData', function () {
  return  gulp.src('./src/app/components/myservice.js')
  .pipe($.inject(gulp.src(['./src/app/components/data.json']), {
      starttag: '/* inject:json */',
      endtag: '/* endinject */'
  }))

  .pipe(gulp.dest("./src"));
});
```

and, of course, nothing happens ;) I *do* get a **./src/myservice.js** file, but has the same contents as the original (ie no injection)

what am I doing wrong ?

thanks

**Comment by Kratos-SA** [comment]
I am having the same issue where I cant add my js to another js file for injection.

**Comment by dorjon** [comment]
Hello I am also facing issue but not similar I want to inject variable to JS file. so how can I achieve this.
