### ISSUE TITLE
Replacing path when injecting

### ISSUE THREAD

**Issue by webchaz** [klei/gulp-inject#84]
Is there a way to replace the path or define the path to use when injecting, instead of dynamically setting the path based on its location?

Thanks!

**Comment by webchaz** [comment]
Ok I found that `options.ignorePaths` will work.  I was looking more for the ability to actually define the path, as oppose to ignoring - maybe that's still an option? But using `options.ignorePaths` does the job

**Comment by joakimbeng** [comment]
@webchaz great that `options.ignorePaths` did the trick. Have a look at the [wiki about injected paths](https://github.com/klei/gulp-inject/wiki/Clarifying-injected-paths) as well.

If you wan't to modify the paths completely before injecting take a look at the `transform` option.
