### ISSUE TITLE
Add possibility to add Attributes

### ISSUE THREAD

**Issue by IbeVanmeenen** [klei/gulp-inject#86]
It would be nice if you could easely add attributes.
As in, add async or defer attribute to script tags for example.

```<script src="demo_async.js" async></script>```

**Comment by gibletto** [comment]
You can overwrite the transform.

````
var transform = function (filepath, file, i, length) {
    return '<script src="' + filepath + '" async></script>';
}

inject(source,{transform transform});
````

**Comment by tillberg** [comment]
Thanks @gibletto -- I came across this thread with the same issue, and your suggestion worked great!

**Comment by joakimbeng** [comment]
Closing this then...

**Comment by IbeVanmeenen** [comment]
Just saw your answer now, thx @gibletto !

**Comment by danielmeng07** [comment]
Hmm doesn't seem to be working for me. Am I doing something wrong? 

```
var transform = function (filepath, file, i, length) {
        return '<script src="' + filepath + '" async></script>';
    }
return gulp.src('source/index.html')
.pipe(gp_inject(app_library, { ignorePath: 'public/', addRootSlash: false, name: 'app_library', transform: transform }))
// .. other pipe, then destination etc. 
```

**Comment by marnusw** [comment]
I just found myself wanting to add the `async` attribute and came across this issue. While overwriting the transform function is certainly easy enough, having `async` and `defer` as boolean options passed to `inject()` would certainly be a nice feature. I think grasping the intent from the code is much easier looking at

```javascript
inject(sources, {async: true, defer: true})
```

than

```javascript
var transform = function (filepath, file, i, length) {
    return '<script src="' + filepath + '" async></script>';
}
inject(source,{transform: transform});
```
That said, I haven't looked at the source code, so I have no idea if it's structured such that this would be an "easy" change. I might look into it at some point and open a PR if there aren't objections to the idea here in the mean time.

**Comment by uliporeggia** [comment]
This issue is very old but I think there is a lot of people ending up here as happend with me.

There is a much easier solution for this, just add `async` or whatever attribute you want in the end of 
placeholder comment tag, like:

```html
    <!-- build:js scripts/vendor.js async charset="utf-8" -->
```

the result is:

```html
    <script src="scripts/vendor.js" async charset="utf-8"></script>
```

**Comment by apaatsio** [comment]
In ES6 the transform function becomes readable.

```javascript
inject(sources, {
  transform: filepath => `<script async src="${filepath}"></script>`
})
``` 

Nevertheless, I vote for the async and defer as option params, because it is such a common use case.

**Comment by ceiger89** [comment]
Or change default template for html -> js

```
gulp.task('html', () => {
  inject.transform.html.js = filepath => `<script src="${filepath}" async></script>`;

    return gulp.src('./src/index.html')
        .pipe(inject(gulp.src(['./dev/js/*.js', './dev/css/*.css'], {read: false}), {
            removeTags: true,
            ignorePath: 'dev',
            addRootSlash: false
        }))
        .pipe(gulp.dest('dev'))
});
```
