### ISSUE TITLE
Remove injection placeholders option?

### ISSUE THREAD

**Issue by johnnyreilly** [klei/gulp-inject#90]
Hi all,

Thanks for gulp-inject - it's absolutely fabulous!  

**Question:** I was wondering if gulp-inject provided a a way to remove injection placeholders as part of the injection process?  This would mean that the final processed file didn't have the `
  ` etc tags post processing.

I've had a read through the docs and I don't think you support this at present - do think it's something that you might consider? Obviously this only caters for the workflow where you copy across your source file(s) before injecting them.  But I think this is a fairly common approach (certainly it is the one I use in my own gulp tasks).

**Comment by gibletto** [comment]
It was merged a few days ago, it now supports options.removeTags:true, not released to npm yet.

**Comment by johnnyreilly** [comment]
Great!  Any idea when it will be released to npm?

**Comment by gibletto** [comment]
Nope! I use it as well, so waiting on it myself :)

**Comment by joakimbeng** [comment]
Sorry for the delay! Forgot to publish.
I've published `v.1.2.0` now where this is included.

**Comment by johnnyreilly** [comment]
Thanks chap!  I can confirm it works a treat :+1:
